title: Prompt Wrangler
description: Safari extension that detects and anonymizes sensitive data in ChatGPT chat prompts
author: Igor Putina
email: igorputina@hey.com

# GitHub Pages settings
baseurl: "/prompt-wrangler-safari"
url: "https://preist.github.io"

# Build settings
markdown: kramdown
